spring:
  application:
    name: mix-one
  profiles:
    active: dev
server:
  port: 8090
  ssl:
    clientAuth: want
    protocol: TLS
    enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,text/css,text/plain,application/javascript
    min-response-size: 2048
    excluded-user-agents: gozilla,traviata
  session:
    timeout: 7200
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
